# Site settings
title: Trophic Nexus Bioinformatics Consulting
email: josh@trophicnexus.com
url: https://trophicnexus.com
description: "I provide bioinformatics support for preclinical biotech startups, offering services from infrastructure deployment and pipeline development to data analysis and algorithm design. My research background is in microbial genomics and the microbiome, enabling deep insight into complex biological data."
meta_author: Joshua J Hamilton

# Contact form:
# pass through formspree.io to validate email sending
contact: static

# Color settings (hex-codes without the leading hash-tag)
# From https://www.schemecolor.com/blue-gray-color-scheme.php
color:
  ateneo-blue: 003B6D
  ateneo-blue-rgb: "0, 59, 109"
  blue-gray: 6699CC
  blue-gray-rgb: "102, 153, 204"
  bright-gray: EBEDF3
  bright-gray-rgb: "235, 237, 243"
  x11_gray: BDBDBD
  x11_gray-rgb: "189, 189, 189"
  granite_gray: 676767
  granite_gray-rgb: "103, 103, 103"

# Footer settings
footer:
  copyright: Joshua J. Hamilton
  contact: Contact
  social: Social Media

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/joshamilton
  - title: github
    url: http://github.com/joshamilton
  - title: google scholar
    url: https://scholar.google.com/citations?hl=en&user=0wdKuE8AAAAJ&view_op=list_works&sortby=pubdate

# Postal address (add as many lines as necessary)
contact:
  - line: Joshua J. Hamilton, PhD
  - line: josh@trophicnexus.com

# Build settings
markdown: kramdown
permalink: pretty

#for projects and services
defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      permalink: "/projects/:title/"
  - scope:
      path: "_services"
      type: "services"
    values:
      permalink: "/projects/:title/"

collections:
  projects:
    output: true
  services:
    output: true